image: ruby

cache:
  paths:
  - vendor/

before_script:
  - bundle install --path vendor

build:
  stage: build
  script:
    - JEKYLL_ENV=production bundle exec jekyll build -d public/
  artifacts:
    when: on_success
    paths:
      - public
  only:
  - master      


pages:
  stage: deploy
  script:
    - JEKYLL_ENV=production bundle exec jekyll build -d public
  artifacts:
    when: on_success
    paths:
    - public
  only:
  - master

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master


stages:
  - build
  - deploy

